      - name: Create IPA
        run: |
          APP_NAME="HassanyBoost"
          mkdir -p Payload/$APP_NAME.app
          cp .theos/obj/$APP_NAME.app/$APP_NAME Payload/$APP_NAME.app/
          
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleExecutable</key>
              <string>HassanyBoost</string>
              <key>CFBundleIdentifier</key>
              <string>com.hassany.boost</string>
              <key>CFBundleName</key>
              <string>Hassany</string>
              <key>UIBackgroundModes</key>
              <array>
                  <string>audio</string>
              </array>
              <key>NSMicrophoneUsageDescription</key>
              <string>نحتاج المايكروفون للتضخيم والتسجيل</string>
              <key>MinimumOSVersion</key>
              <string>14.0</string>
          </dict>
          </plist>' > Payload/$APP_NAME.app/Info.plist
          
          zip -r HassanyBoost.ipa Payload
